[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
squat_program = "CwiWNFEg8j2s3omMvEW8gaQTjhs4CG1uCpAzcGiq7mf9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
